/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as BusBusIdRouteImport } from './routes/bus.$busId'
import { Route as BookBusIdRouteImport } from './routes/book.$busId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusBusIdRoute = BusBusIdRouteImport.update({
  id: '/bus/$busId',
  path: '/bus/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBusIdRoute = BookBusIdRouteImport.update({
  id: '/book/$busId',
  path: '/book/$busId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/conductor': typeof ConductorRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/tickets': typeof TicketsRoute
  '/book/$busId': typeof BookBusIdRoute
  '/bus/$busId': typeof BusBusIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/conductor': typeof ConductorRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/tickets': typeof TicketsRoute
  '/book/$busId': typeof BookBusIdRoute
  '/bus/$busId': typeof BusBusIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/conductor': typeof ConductorRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/tickets': typeof TicketsRoute
  '/book/$busId': typeof BookBusIdRoute
  '/bus/$busId': typeof BusBusIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/conductor'
    | '/login'
    | '/profile'
    | '/routes'
    | '/tickets'
    | '/book/$busId'
    | '/bus/$busId'
    | '/ticket/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/conductor'
    | '/login'
    | '/profile'
    | '/routes'
    | '/tickets'
    | '/book/$busId'
    | '/bus/$busId'
    | '/ticket/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/conductor'
    | '/login'
    | '/profile'
    | '/routes'
    | '/tickets'
    | '/book/$busId'
    | '/bus/$busId'
    | '/ticket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConductorRoute: typeof ConductorRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RoutesRoute: typeof RoutesRoute
  TicketsRoute: typeof TicketsRoute
  BookBusIdRoute: typeof BookBusIdRoute
  BusBusIdRoute: typeof BusBusIdRoute
  TicketIdRoute: typeof TicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus/$busId': {
      id: '/bus/$busId'
      path: '/bus/$busId'
      fullPath: '/bus/$busId'
      preLoaderRoute: typeof BusBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$busId': {
      id: '/book/$busId'
      path: '/book/$busId'
      fullPath: '/book/$busId'
      preLoaderRoute: typeof BookBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConductorRoute: ConductorRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RoutesRoute: RoutesRoute,
  TicketsRoute: TicketsRoute,
  BookBusIdRoute: BookBusIdRoute,
  BusBusIdRoute: BusBusIdRoute,
  TicketIdRoute: TicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
